// Mocks generated by Mockito 5.4.6 from annotations
// in hesap/test/features/settings/presentation/pages/settings_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:flutter_bloc/flutter_bloc.dart' as _i9;
import 'package:hesap/feature/settings/domain/repositories/settings_repository.dart'
    as _i4;
import 'package:hesap/feature/settings/domain/usecases/get_settings.dart'
    as _i2;
import 'package:hesap/feature/settings/domain/usecases/save_settings.dart'
    as _i3;
import 'package:hesap/feature/settings/presentation/bloc/settings_cubit.dart'
    as _i7;
import 'package:hesap/feature/settings/presentation/bloc/settings_state.dart'
    as _i6;
import 'package:hesap/module/notification/notification_service.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGetSettings_0 extends _i1.SmartFake implements _i2.GetSettings {
  _FakeGetSettings_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSaveSetting_1 extends _i1.SmartFake implements _i3.SaveSetting {
  _FakeSaveSetting_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSettingsRepository_2 extends _i1.SmartFake
    implements _i4.SettingsRepository {
  _FakeSettingsRepository_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNotificationService_3 extends _i1.SmartFake
    implements _i5.NotificationService {
  _FakeNotificationService_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSettingsState_4 extends _i1.SmartFake implements _i6.SettingsState {
  _FakeSettingsState_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SettingsCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsCubit extends _i1.Mock implements _i7.SettingsCubit {
  @override
  _i2.GetSettings get getSettings => (super.noSuchMethod(
        Invocation.getter(#getSettings),
        returnValue: _FakeGetSettings_0(
          this,
          Invocation.getter(#getSettings),
        ),
        returnValueForMissingStub: _FakeGetSettings_0(
          this,
          Invocation.getter(#getSettings),
        ),
      ) as _i2.GetSettings);

  @override
  _i3.SaveSetting get saveSetting => (super.noSuchMethod(
        Invocation.getter(#saveSetting),
        returnValue: _FakeSaveSetting_1(
          this,
          Invocation.getter(#saveSetting),
        ),
        returnValueForMissingStub: _FakeSaveSetting_1(
          this,
          Invocation.getter(#saveSetting),
        ),
      ) as _i3.SaveSetting);

  @override
  _i4.SettingsRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeSettingsRepository_2(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeSettingsRepository_2(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i4.SettingsRepository);

  @override
  _i5.NotificationService get notificationService => (super.noSuchMethod(
        Invocation.getter(#notificationService),
        returnValue: _FakeNotificationService_3(
          this,
          Invocation.getter(#notificationService),
        ),
        returnValueForMissingStub: _FakeNotificationService_3(
          this,
          Invocation.getter(#notificationService),
        ),
      ) as _i5.NotificationService);

  @override
  _i6.SettingsState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeSettingsState_4(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeSettingsState_4(
          this,
          Invocation.getter(#state),
        ),
      ) as _i6.SettingsState);

  @override
  _i8.Stream<_i6.SettingsState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i8.Stream<_i6.SettingsState>.empty(),
        returnValueForMissingStub: _i8.Stream<_i6.SettingsState>.empty(),
      ) as _i8.Stream<_i6.SettingsState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i8.Future<void> loadSettings() => (super.noSuchMethod(
        Invocation.method(
          #loadSettings,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> updateCriticalStockThreshold(double? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCriticalStockThreshold,
          [value],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> updateForecastPeriod(int? value) => (super.noSuchMethod(
        Invocation.method(
          #updateForecastPeriod,
          [value],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> updateCriticalStockNotification(bool? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCriticalStockNotification,
          [value],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> updateDailySummary(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #updateDailySummary,
          [value],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> updateProductionForecast(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #updateProductionForecast,
          [value],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> updateDarkMode(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #updateDarkMode,
          [value],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> updateLanguage(String? value) => (super.noSuchMethod(
        Invocation.method(
          #updateLanguage,
          [value],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> clearSettings() => (super.noSuchMethod(
        Invocation.method(
          #clearSettings,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void emit(_i6.SettingsState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i9.Change<_i6.SettingsState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}
