// Mocks generated by Mockito 5.4.6 from annotations
// in hesap/test/features/settings/presentation/bloc/settings_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:hesap/core/errror/failure.dart' as _i6;
import 'package:hesap/core/service/notification_service.dart' as _i9;
import 'package:hesap/features/settings/domain/entities/app_settings.dart'
    as _i7;
import 'package:hesap/features/settings/domain/repositories/settings_repository.dart'
    as _i2;
import 'package:hesap/features/settings/domain/usecases/get_settings.dart'
    as _i4;
import 'package:hesap/features/settings/domain/usecases/save_settings.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSettingsRepository_0 extends _i1.SmartFake
    implements _i2.SettingsRepository {
  _FakeSettingsRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetSettings].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetSettings extends _i1.Mock implements _i4.GetSettings {
  MockGetSettings() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SettingsRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeSettingsRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.SettingsRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.AppSettings>> call() =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, _i7.AppSettings>>.value(
            _FakeEither_1<_i6.Failure, _i7.AppSettings>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.AppSettings>>);
}

/// A class which mocks [SaveSetting].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveSetting extends _i1.Mock implements _i8.SaveSetting {
  MockSaveSetting() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SettingsRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeSettingsRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.SettingsRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call({
    required String? key,
    required dynamic value,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #key: key,
            #value: value,
          },
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
            _FakeEither_1<_i6.Failure, void>(
          this,
          Invocation.method(
            #call,
            [],
            {
              #key: key,
              #value: value,
            },
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, void>>);
}

/// A class which mocks [SettingsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsRepository extends _i1.Mock
    implements _i2.SettingsRepository {
  MockSettingsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.AppSettings>> getSettings() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSettings,
          [],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, _i7.AppSettings>>.value(
            _FakeEither_1<_i6.Failure, _i7.AppSettings>(
          this,
          Invocation.method(
            #getSettings,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.AppSettings>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> saveSetting(
    String? key,
    dynamic value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSetting,
          [
            key,
            value,
          ],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
            _FakeEither_1<_i6.Failure, void>(
          this,
          Invocation.method(
            #saveSetting,
            [
              key,
              value,
            ],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> clearSettings() =>
      (super.noSuchMethod(
        Invocation.method(
          #clearSettings,
          [],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
            _FakeEither_1<_i6.Failure, void>(
          this,
          Invocation.method(
            #clearSettings,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, void>>);
}

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i9.NotificationService {
  MockNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> requestPermission() => (super.noSuchMethod(
        Invocation.method(
          #requestPermission,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> showCriticalStockNotification({
    required String? productName,
    required double? threshold,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showCriticalStockNotification,
          [],
          {
            #productName: productName,
            #threshold: threshold,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> scheduleDailySummary({required bool? enabled}) =>
      (super.noSuchMethod(
        Invocation.method(
          #scheduleDailySummary,
          [],
          {#enabled: enabled},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> scheduleProductionForecast({required bool? enabled}) =>
      (super.noSuchMethod(
        Invocation.method(
          #scheduleProductionForecast,
          [],
          {#enabled: enabled},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> cancelAll() => (super.noSuchMethod(
        Invocation.method(
          #cancelAll,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> applySettings({
    required bool? criticalStockNotification,
    required bool? dailySummary,
    required bool? productionForecast,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #applySettings,
          [],
          {
            #criticalStockNotification: criticalStockNotification,
            #dailySummary: dailySummary,
            #productionForecast: productionForecast,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
