// Mocks generated by Mockito 5.4.6 from annotations
// in hesap/test/features/stock/presentation/bloc/daily_entry_cubit_load_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dartz/dartz.dart' as _i3;
import 'package:hesap/core/errror/failure.dart' as _i7;
import 'package:hesap/features/product/domain/entities/product.dart' as _i8;
import 'package:hesap/features/product/domain/repositories/product_repository.dart'
    as _i2;
import 'package:hesap/features/product/domain/usecases/get_all_products_usecase.dart'
    as _i5;
import 'package:hesap/features/stock/domain/entities/daily_stock_entry.dart'
    as _i10;
import 'package:hesap/features/stock/domain/repositories/daily_entry_repository.dart'
    as _i4;
import 'package:hesap/features/stock/domain/usecases/get_last_entry_usecase.dart'
    as _i11;
import 'package:hesap/features/stock/domain/usecases/save_daily_entries_usecase.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeProductRepository_0 extends _i1.SmartFake
    implements _i2.ProductRepository {
  _FakeProductRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDailyEntryRepository_2 extends _i1.SmartFake
    implements _i4.DailyEntryRepository {
  _FakeDailyEntryRepository_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetAllProductsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllProductsUseCase extends _i1.Mock
    implements _i5.GetAllProductsUseCase {
  MockGetAllProductsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ProductRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeProductRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ProductRepository);

  @override
  _i6.Future<_i3.Either<_i7.Failure, List<_i8.Product>>> call() =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue:
            _i6.Future<_i3.Either<_i7.Failure, List<_i8.Product>>>.value(
                _FakeEither_1<_i7.Failure, List<_i8.Product>>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i6.Future<_i3.Either<_i7.Failure, List<_i8.Product>>>);
}

/// A class which mocks [SaveDailyEntriesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveDailyEntriesUseCase extends _i1.Mock
    implements _i9.SaveDailyEntriesUseCase {
  MockSaveDailyEntriesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.DailyEntryRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeDailyEntryRepository_2(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i4.DailyEntryRepository);

  @override
  _i6.Future<_i3.Either<_i7.Failure, _i3.Unit>> call(
          List<_i10.DailyStockEntry>? entries) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [entries],
        ),
        returnValue: _i6.Future<_i3.Either<_i7.Failure, _i3.Unit>>.value(
            _FakeEither_1<_i7.Failure, _i3.Unit>(
          this,
          Invocation.method(
            #call,
            [entries],
          ),
        )),
      ) as _i6.Future<_i3.Either<_i7.Failure, _i3.Unit>>);
}

/// A class which mocks [GetLastEntryForProductUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetLastEntryForProductUseCase extends _i1.Mock
    implements _i11.GetLastEntryForProductUseCase {
  MockGetLastEntryForProductUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.DailyEntryRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeDailyEntryRepository_2(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i4.DailyEntryRepository);

  @override
  _i6.Future<_i3.Either<_i7.Failure, _i10.DailyStockEntry?>> call(
          String? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [productId],
        ),
        returnValue:
            _i6.Future<_i3.Either<_i7.Failure, _i10.DailyStockEntry?>>.value(
                _FakeEither_1<_i7.Failure, _i10.DailyStockEntry?>(
          this,
          Invocation.method(
            #call,
            [productId],
          ),
        )),
      ) as _i6.Future<_i3.Either<_i7.Failure, _i10.DailyStockEntry?>>);
}
