// Mocks generated by Mockito 5.4.6 from annotations
// in hesap/test/features/stock/data/repositories/daily_entry_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:hesap/features/stock/data/datasources/daily_entry_datasource.dart'
    as _i2;
import 'package:hesap/features/stock/domain/entities/daily_stock_entry.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [DailyEntryLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockDailyEntryLocalDatasource extends _i1.Mock
    implements _i2.DailyEntryLocalDatasource {
  MockDailyEntryLocalDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveDailyEntries(List<_i4.DailyStockEntry>? entries) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveDailyEntries,
          [entries],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.DailyStockEntry>> getEntriesByDate(DateTime? date) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEntriesByDate,
          [date],
        ),
        returnValue: _i3.Future<List<_i4.DailyStockEntry>>.value(
            <_i4.DailyStockEntry>[]),
      ) as _i3.Future<List<_i4.DailyStockEntry>>);

  @override
  _i3.Future<_i4.DailyStockEntry?> getLastEntryForProduct(String? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLastEntryForProduct,
          [productId],
        ),
        returnValue: _i3.Future<_i4.DailyStockEntry?>.value(),
      ) as _i3.Future<_i4.DailyStockEntry?>);
}
