// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:hesap/core/models/daily_stock_entry_model.dart';
import 'package:hesap/core/models/product_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(DailyStockEntryModelAdapter());
    registerAdapter(ProductModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(DailyStockEntryModelAdapter());
    registerAdapter(ProductModelAdapter());
  }
}
